# Stubs for pydpiper.core.files (Python 3.5)

import typing

class FileAtom:
    orig_path = ... # type: str
    pipeline_sub_dir = ... # type: str
    output_sub_dir = ... # type: str
    def __init__(self, name, orig_name=..., pipeline_sub_dir=None, output_sub_dir=None) -> None: ...
    def __eq__(self, other) -> bool: ...
    def get_path(self) -> str: ...
    path = ... # type: str
    def get_basename(self) -> str: ...
    def newname_with_fn(self, fn, ext=None, subdir=None): ...
    def newname_with_suffix(self, suffix, ext=None, subdir=None): ...
