# Stubs for pydpiper.core.util (Python 3.5)

from typing import TypeVar, Set, Sequence, Tuple

from pydpiper.execution.pipeline import CmdStage # type: ignore

T = TypeVar('T')

def raise_(err : BaseException): ...
def explode(filename : str): ...
def pairs(lst : Sequence[T]) -> Sequence[Tuple[T, T]]: ...
def flatten(*xs): ...

class NotProvided(BaseException): ...
class NoneError(ValueError): ...

def ensure_nonnull_return(f): ...
def mkdir_p(path : str) -> None: ...
def output_directories(stages : Set[CmdStage]) -> Set[str]: ...
