# Stubs for pydpiper.minc.containers (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class XfmHandler:
    source = ... # type: Any
    xfm = ... # type: Any
    target = ... # type: Any
    def __init__(self, source, xfm, target, resampled=None): ...
    resampled = ... # type: Any
